#!/usr/bin/env python3

"""
usage:
  gen <width> <height> <filename> [--method=<method>]
  gen (-h | --help)

options:
  -h --help           displays this page.
  --method=<method>   choose a generation method, one of:
                        pr (prims, default),
                        rb (recursive backtrack)
"""

from libmaze.vendor.docopt import docopt
from libmaze.generate import prims, recursive_backtrack
from libmaze.plot import plot_path, plot_heatmap
from libmaze.read import maze_from_file
import json


def get_generator(string):
    return {
        'pr': prims,
        'rb': recursive_backtrack,
        }.get(string, prims)


if __name__ == '__main__':
    args   = docopt(__doc__)
    dst    = args['<filename>'] + '.png'
    dstjson = args['<filename>'] + '.json'
    width  = int(args['<width>'])
    height = int(args['<height>'])
    generate = get_generator(args['--method'])
    plot_path(
        generate(width, height),
        [],
        ).save(dst)
    maze = maze_from_file(dst)
    i = maze.array[0].index(1)
    maze.array[0] = maze.array[0][:i] + [2] + maze.array[0][i+1:]
    j = maze.array[-1].index(1)
    maze.array[-1] = maze.array[-1][:j] + [3] + maze.array[-1][j+1:]
    with open(dstjson, 'w') as f:
    	json.dump(maze.array, f)
