#!/usr/bin/env python

"""
usage:
  maze <width> <height> <filename> [--solver=<solver>]
  maze (-h | --help)

options:
  -h --help           displays this page.
  --solver=<solver>   choose which solver to use, one of:
                        bf (breadth first, default),
                        rm (random mouse)
"""

from docopt import docopt
from mt import maze_transform
from solvers import random_mouse, breadth_first
from mazegen import gen
from vis import plot_path, plot_heatmap


def get_solver_plotter(string):
    default = {
        'bf': (breadth_first, plot_path),
        'rm': (random_mouse,  plot_heatmap),
    }
    return default.get(string, default['bf'])


if __name__ == '__main__':
    args = docopt(__doc__)
    filename = args['<filename>']
    width = int(args['<width>'])
    height = int(args['<height>'])
    maze = gen(width, height)
    solver, plotter = get_solver_plotter(args['--solver'])
    path = solver(*maze_transform(maze))
    plotter(
        maze,
        path,
        filename,
        )
