#!/usr/bin/env python

"""
usage:
  maze gen <width> <height> <filename>
  maze solve <src> <dst> [--solver=<solver>]
  maze (-h | --help)

options:
  -h --help           displays this page.
  --solver=<solver>   choose which solver to use, one of:
                        bf (breadth first, default),
                        df (depth first),
                        rm (random mouse)
"""

from libmaze.vendor.docopt import docopt
from libmaze.generate import generate
from libmaze.transform import transform
from libmaze.solvers import random_mouse, breadth_first, depth_first
from libmaze.plot import plot_path, plot_heatmap
from libmaze.read import maze_from_file


def get_solver_plotter(string):
    default = {
        'bf': (breadth_first, plot_path),
        'df': (depth_first,   plot_path),
        'rm': (random_mouse,  plot_heatmap),
    }
    return default.get(string, default['bf'])


def gen(args):
    filename = args['<filename>']
    width    = int(args['<width>'])
    height   = int(args['<height>'])
    plot_path(
        generate(width, height),
        [],
        ).save(filename)


def solve(args):
    src = args['<src>']
    dst = args['<dst>']
    maze = maze_from_file(src)
    solver, plotter = get_solver_plotter(args['--solver'])
    path = solver(*transform(maze))
    plotter(
        maze,
        path,
        ).save(dst)


if __name__ == '__main__':
    args = docopt(__doc__)
    if args['gen']:
        gen(args)
    elif args['solve']:
        solve(args)
