#!/usr/bin/env python

"""
usage: maze <width> <height> <filename>
"""

import sys
from mt import maze_transform, breadth_first
from mazegen import gen
from vis import plot_maze_path

if __name__ == '__main__':
    try:
        _, width, height, filename = sys.argv
    except ValueError:
        print(__doc__)
        exit(1)
    width = int(width)
    height = int(height)
    maze = gen(width, height)
    path = breadth_first(*maze_transform(maze))
    plot_maze_path(
        maze,
        path,
        filename,
        )
